name: regenerate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: corepack enable

      - run: pnpm install

      - run: pnpm lint

      - run: pnpm build

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - run: pnpm start
        id: fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        if: ${{ steps.fetch.outputs.updated == 'true' }}
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update Plugin to Version ${{ steps.fetch.outputs.version }} with Commit skotlex/ffxiv-material-ui@${{ steps.fetch.outputs.master }} & sevii77/ffxiv_materialui_accent@${{ steps.fetch.outputs.accent }}
